SouqElGomalAdmin/Controllers/orderController.cs
using PagedList;
using SouqElGomalAdmin.Repository;
using SouqElGomalAdmin.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SouqElGomalAdmin.Controllers
{
    public class orderController : Controller
    {
        List<ProductOrderModel> productsOrderID = new List<ProductOrderModel>();
        List<HelpInOrder> productsOrder = new List<HelpInOrder>();
        float TotalPrice =0;

        // GET: order
        public ActionResult Index(int? page, string SearchBy = "ID", string Search = "")
        {
            ////////////////////////////////
            if (Session["admin"] == null)
                return Redirect("/admin/login");
            ////////////////////////////////
            ///

            List<OrderModel> res = new List<OrderModel>();

            if (SearchBy == "ID")
            {
                if (Search == "")
                {
                    res = OrderRepo.GetAll().ToList();
                }
                else
                {
                    res = OrderRepo.GetAll().Where(i => i.ID == int.Parse(Search)).ToList();
                }
            }

            return View(res.ToPagedList(page ?? 1, 7));
        }





        public ActionResult Order_details(int ID)
        {
            ////////////////////////////////
            if (Session["admin"] == null)
                return Redirect("/admin/login");
            ////////////////////////////////

            OrderModel res = OrderRepo.GetAll().FirstOrDefault(i => i.ID == ID);
            UserModel temp4 = UserRepo.GetAll().FirstOrDefault(z => z.ID == res.UserId);

            foreach (var i in res.ProductOrders)
            {
                ProductOrderModel val = new ProductOrderModel();
                val.ProductID  = i.ProductID;
                val.Quantity = i.Quantity;
                val.ID = i.ID;
                productsOrderID.Add(val);
            }

            foreach (var i in productsOrderID)
            {
                HelpInOrder temp = new HelpInOrder();
                ProductModel temp2 = ProductRepo.GetAll().FirstOrDefault(x => x.ID == i.ProductID);
                ProductOrderModel temp3 = ProductOrderRepo.GetAll().FirstOrDefault(y => y.ProductID == temp2.ID);
                

                temp.NameOfProduct = temp2.Name;
                temp.PriceOfProduct = temp2.Price;
                temp.QuantityOfProduct = temp3.Quantity;
                temp.TotalPriceOfProduct = temp.QuantityOfProduct * temp.PriceOfProduct;
                TotalPrice += temp.TotalPriceOfProduct;

                productsOrder.Add(temp);
 
            }


            ViewBag.User = temp4;
            TempData["TotalPrice"] = TotalPrice;
            TempData["Prod"] = productsOrder;
            return View(res);
        }


        public ActionResult Accepted(OrderModel editOredr)
        {
            ////////////////////////////////
            if (Session["admin"] == null)
                return Redirect("/admin/login");
            ////////////////////////////////
            ///

            editOredr.State = 1;
            OrderRepo.Edit(editOredr);

            return Redirect("/order/Index");
        }
        public ActionResult Deliverd(OrderModel editOredr)
        {
            ////////////////////////////////
            if (Session["admin"] == null)
                return Redirect("/admin/login");
            ////////////////////////////////
            ///

            editOredr.State = 2;
            OrderRepo.Edit(editOredr);

            return Redirect("/order/Index");
        }
    }
}

SouqElGomalAdmin/Views/order/Index.cshtml
@using SouqElGomalAdmin.ViewModels
@using PagedList.Mvc;
@using PagedList;
@model IPagedList<OrderModel>


<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>SougEl-Gomla Admin</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sidebars/">

    <!-- CSS W3 Animation -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="://fonts.googleapis.com/css2?family=Poppins:weight@100;200;300;400;500;600;700;800&display=swap" />
    <!-- Bootstrap Custom styles for this template -->
    <link href="sidebars.css" rel="stylesheet">

    <!--forms style-->
    <style>
        h4 {
            text-align: center;
            font-weight: bold;
        }

        .btn {
            background-color: #ed872f;
            border: #ed872f;
            color: white;
        }

            .btn:hover {
                background-color: #b54c26;
                border: #b54c26;
                color: white;
            }

            .btn.delete {
                background-color: #DC3645;
                border: #DC3645;
                color: white;
            }

                .btn.delete:hover {
                    background-color: #BC2E3C;
                    border: #BC2E3C;
                    color: white;
                }

        .container {
            background-color: #efffed;
        }

        #formcontainer,
        .card {
            background-color: #d2e7cf;
        }

        i {
            color: #ed872f;
        }

        .active {
            color: #50b141;
            text-decoration: none;
        }

            .active i {
                color: #50b141;
            }

        .nav-link {
            color: #ed872f;
        }

            .nav-link:hover {
                color: #b54c26;
            }

        * {
            font-family: Arial, Helvetica, sans-serif;
        }
        /*# sourceMappingURL=style.css.map */
    </style>

    <style>
        #formcontainer {
            margin: 0 auto;
        }


        .pagination > .active > a:not([href]):not([class]), a:not([href]):not([class]):hover {
            color: #fff;
            background-color: #f98152;
            margin: 3px;
            padding: 7px 10px;
            text-decoration: none;
        }

        .pagination > li > a {
            color: #fff;
            background-color: #fb9b50;
            margin: 3px;
            padding: 7px 10px;
            text-decoration: none;
        }
        b{
            font-weight:bold;
        }
    </style>

    <style>


        body {
            background-color: #eee;
            font-family: "Poppins", sans-serif;
            font-weight: 300
        }

        .search {
            position: relative;
            box-shadow: 0 0 40px rgba(51, 51, 51, .1)
        }

            .search input {
                height: 60px;
                text-indent: 25px;
                border: 2px solid #d6d4d4
            }

                .search input:focus {
                    box-shadow: none;
                    border: 2px solid blue
                }

            .search .fa-search {
                position: absolute;
                top: 20px;
                left: 16px
            }

            .search button {
                position: absolute;
                top: 5px;
                right: 5px;
                height: 50px;
                width: 110px;
                background: blue
            }

        @@media(min-width: 481px) and (max-width: 767px) {
            col-12.col-md-10.mt-2.mb-2.border.border-1.rounded {
                width: 90%
            }
        }
    </style>
</head>
<!------------------------------------------------------------------------------------------------->
<body style=" background-color: #DEDEDE " onload="BarFunction();" class="active">


    <div class="row">

        <div >

            @Html.Partial("_SideBar2");
        </div>

        <div class="col-12">
            <!--Get Products-->
            <div class="row mt-4">
                <div class="col-12 col-md-10 mt-2 mb-2 border border-1 rounded" id="formcontainer" style="background-color: #fff">
                    <h4 class="mt-4">Orders</h4>
                    <hr />

                    @using (Html.BeginForm("Index", "order", FormMethod.Get, new { @class = "form-control" }))
                    {

                        <span><input type="text" placeholder="Search By ID" name="Search" class="form-control" style="width:300px; float:left;" /></span>

                        <span><input type="submit" value="Search" class="btn btn-primary" /></span>
                    }

                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">Order ID</th>
                                <th scope="col">Date</th>
                                <th scope="col">Status</th>
                                <th scope="col">Details</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var i in Model)
                            {
                                <tr>

                                    <td>@i.ID</td>
                                    <td>@i.OrderDate</td>

                                    @if (i.State == 0)
                                    {
                                        <td><div style="width: 10px; height: 10px; border-radius: 50px; background-color: darkgoldenrod; Display:inline-block;"></div><b style="color:darkgoldenrod;"> Pending</b></td>
                                    }
                                    @if (i.State == 1)
                                    {
                                        <td><div style="width: 10px; height: 10px; border-radius: 50px; background-color: blue; Display:inline-block;"></div><b style="color:blue;"> On The Way</b></td>
                                    }
                                    @if (i.State == 2)
                                    {
                                        <td><div style="width: 10px; height: 10px; border-radius: 50px; background-color: green; Display:inline-block;"></div><b style="color:green;"> Delivard</b></td>
                                    }

                                    <th>@Html.ActionLink("Details", "Order_details", new { id = i.ID }, new { @class = "btn btn-primary" })</th>


                                </tr>
                            }
                        </tbody>
                    </table>
                    <div id="Buttons">
                        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
                    </div>
                </div>
            </div>


        </div>
    </div>
    <script>
        function BarFunction() {
            document.getElementById('Show_Orders').setAttribute("class", "nav-link text-white active");
            document.getElementById('Show_Orders_icon').setAttribute("class", "nav-link  active");
        }
    </script>

    <!------------------------------------------------------------------------------------------------->
    <!--Bootstrap js-->
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script>
        /* global bootstrap: false */
        (function () {
            'use strict'
            var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
            tooltipTriggerList.forEach(function (tooltipTriggerEl) {
                new bootstrap.Tooltip(tooltipTriggerEl)
            })
        })()

    </script>

    <!------------------------------------------------------------------------------------------------->

</body>
</html>

SouqElGomalAdmin/Views/order/Order_details.cshtml
@using SouqElGomalAdmin.ViewModels
@model OrderModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SougEl-Gomla Admin</title>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>

    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        input {
            width: 50%;
        }

        tr:nth-child(odd) {
            background-color: #dfdfdf;
            width: 100%;
        }

        tr:nth-child(even) {
            background-color: #fff;
            width: 100%;
        }


        td {
            padding: 10px 20px;
        }

        #price {
            margin: 0 auto;
            text-align: center;
            padding: 10px 0;
        }

        #btn {
            border: solid 1px #b54c26;
            background-color: #b54c26;
            padding: 0 10px;
            color: white;
            border-radius: 3rem;
            height: 48px;
            width: 200px;
        }

            #btn:hover {
                border: solid 1px #ed872f;
                background-color: #ed872f;
            }

        #img {
            float: right;
            width: 500px;
        }

        #main {
            width: 70%;
            margin: 0 auto;
            text-align: left;
            padding-top: 50px;
        }

        #main2 {
            width: 70%;
            margin: 0 auto;
            padding-top: 20px;
        }

        @@media (min-width: 481px) and (max-width: 767px) {
            #img {
                width: 350px;
                float: right;
            }

            #btn {
                padding: 0 10px;
                color: white;
                border-radius: 3rem;
                height: 48px;
                font-size: 15px;
                width: 150px;
            }

            #main2 {
                width: 100%;
                margin: 0 auto;
                padding-top: 20px;
            }
        }

        @@media (min-width: 768px) and (max-width: 1024px) {
            #img {
                width: 400px;
                float: right;
            }

            #btn {
                padding: 0 10px;
                color: white;
                border-radius: 3rem;
                height: 48px;
                font-size: 15px;
                width: 200px;
            }

            #main2 {
                width: 100%;
                margin: 0 auto;
                padding-top: 20px;
            }
        }
    </style>
</head>
<body style=" background-color: #DEDEDE ">

    <div class="row">

        <div class="col-1"></div>
        <div class="col-10 col-md-10 mt-2 mb-2 border border-1 rounded" id="formcontainer" style="background-color: #fff">

            <div id="main">
                <div style="margin:50px 0;">
                    <h1>Invioce</h1>
                    <h6 style="display:inline-block;">Date:@Model.OrderDate <h6 id="demo" style="display:inline-block;"></h6></h6>
                    <h6><b>No.: </b>@Model.ID</h6>
                    <h6><b>User Name: </b>@ViewBag.User.Name</h6>
                    <h6><b>Email: </b>@ViewBag.User.Email</h6>
                    <h6><b>Phone Number: </b>@ViewBag.User.PhoneNumber</h6>
                    <h6><b>Address: </b>@ViewBag.User.Address</h6>
                    @if (Model.PaymentMethod == 1)
                    {
                        <h6><b>Payment Method: </b>Cash</h6>
                    }
                    else
                    {
                        <h6><b>Payment Method: </b>Paypal</h6>
                    }

                </div>
            </div>

            <div id="main2">
                <table width="100%" id="table">
                    <tr>
                        <th style="padding:10px 20px;">Product</th>
                        <th style="padding:10px 20px;">Quantity</th>
                        <th style="padding:10px 20px;">Price</th>
                        <th style="padding:10px 20px;">Total</th>
                    </tr>
                    @foreach (var i in (List<HelpInOrder>)TempData["Prod"])
                    {
                        <tr>
                            <td>@i.NameOfProduct</td>
                            <td>@i.QuantityOfProduct</td>
                            <td>@i.PriceOfProduct</td>
                            <td>@i.TotalPriceOfProduct</td>
                        </tr>
                    }

                </table>
                <hr />
            </div>

            <div style="width:70%; margin:30px auto; text-align:left;">
                <h4 style="float:left; margin-right:10px;">Total:@((float)TempData["TotalPrice"])</h4>

            </div>



            <div class="row" style="margin-top:120px; margin-bottom:50px;">
                <div class="col-3"></div>

                <div class="col-4">


                    @if (Model.State == 0)
                    {
                        using (Html.BeginForm("Accepted", "order", "POST"))
                        {
                            @Html.TextBoxFor(i => i.ID, new { @type = "hidden" });
                            @Html.TextBoxFor(i => i.State, new { @type = "hidden" });

                            <input type="submit" class="btn btn-primary" Value="Accept Order" />
                        }
                    }

                    @if (Model.State == 1)
                    {
                        using (Html.BeginForm("Deliverd", "order", "POST"))
                        {
                            @Html.TextBoxFor(i => i.ID, new { @type = "hidden" });
                            @Html.TextBoxFor(i => i.State, new { @type = "hidden" });

                            <input type="submit" class="btn btn-success" Value="Deliverd" />
                        }
                    }


                </div>
                <div class="col-2">
                    <a href="/order/Index">
                        <div class="btn" style="background-color:#ed872f; color:white;">
                            Back
                        </div>
                    </a>
                </div>

                <div class="col-3"></div>

            </div>
        </div>

        <div class="col-1"></div>

    </div>

</body>
</html>