SouqElGomalAdmin/Models/ProductType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SouqElGomalAdmin.Models
{
    public class ProductType
    {

        [Display(Name = "ID")]
        public int ID { get; set; }

        [Required(ErrorMessage = "*Name Required")]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "*Description Required")]
        [Display(Name = "Description ")]
        public string Description { get; set; }

        [Required(ErrorMessage = "*Price Required")]
        [Display(Name = "Price")]
        public float Price { get; set; }

        [Required(ErrorMessage = "*Quantity Required")]
        [Display(Name = "Quantity")]
        public int Quantity { get; set; }

        [Required(ErrorMessage = "*UnitWeight Required")]
        [Display(Name = "UnitWeight")]
        public string UnitWeight { get; set; }


        [Display(Name = "Image")]
        [Required(ErrorMessage = "*Image Required")]
        public byte[] Image { get; set; }


        [Display(Name = "UserId")]
        public string UserId { get; set; }

        [Required(ErrorMessage = "*Category Required")]
        public int CategoryID { get; set; }

    }
}

SouqElGomalAdmin/Controllers/productController.cs
using SouqElGomalAdmin.Repository;
using SouqElGomalAdmin.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;
using SouqElGomalAdmin.Models;

namespace SouqElGomalAdmin.Controllers
{
    public class productController : Controller
    {
        // GET: product
        public ActionResult Index(int? page, string SearchBy = "",  string Search = "", string Category = "")
        {
            ////////////////////////////////
            if (Session["admin"] == null)
                return Redirect("/admin/login");
            ////////////////////////////////
            ///

            List<ProductModel> res = new List<ProductModel>();

            try
            {

            ViewBag.cat1 = new SelectList(CategoryRepo.GetAll(), "ID", "Name");     // get All Categories

                if (Search == "" && Category == "")                              // Filter
                 {
                    res = ProductRepo.GetAll().ToList();
                }
                else if (Search.Length > 0 && Category == "")
                {
                    res = ProductRepo.GetAll().Where(i => i.Name.Contains(Search) || Search == null).ToList();
                }
                else if (Category.Length > 0 && Search == "")
                {
                     res = ProductRepo.GetAll().Where(i => i.CategoryID == int.Parse(Category)).ToList();
                }
                else 
                {
                    res = ProductRepo.GetAll().Where(i => i.CategoryID == int.Parse(Category)).ToList();
                    res = res.Where(i => i.Name.Contains(Search) || Search == null).ToList();
                }
            }
            catch(Exception ex)
            {
                TempData["alert"] = 5;
            }

            return View(res.ToPagedList(page ?? 1, 7));
        }



        [HttpGet]
        public ActionResult Add_Product()
        {
            ////////////////////////////////
            if (Session["admin"] == null)
                return Redirect("/admin/login");
            ////////////////////////////////
            ///

            ViewBag.cat2 = new SelectList(CategoryRepo.GetAll(), "ID", "Name");     //for category dropDownList
            return View();
        }


        [HttpPost]
        public ActionResult Add_product(ProductModel NewProd, HttpPostedFileBase Image1, string unit)
        {

            ////////////////////////////////
            if (Session["admin"] == null)
                return Redirect("/admin/login");
            ////////////////////////////////
            ///


            try
            {
                foreach (var i in ProductRepo.GetAll())                              //check for Name unique
                {
                    if (NewProd.Name == i.Name)
                    {
                        ViewBag.existingName2 = "*This Product Is Already Existing";
                        ViewBag.cat2 = new SelectList(CategoryRepo.GetAll(), "ID", "Name");
                        return View();
                    }
                }


                Product temp = new Product();                             //check Validation


                if (!ModelState.IsValid)
                {
                    ViewBag.cat2 = new SelectList(CategoryRepo.GetAll(), "ID", "Name");
                    return View();
                }
                else
                {
                    if (Image1 != null)                                                        // becouse if image null it will make error so this code for that
                    {
                        NewProd.Image = new byte[Image1.ContentLength];
                        Image1.InputStream.Read(NewProd.Image, 0, Image1.ContentLength);

                        temp.Name = NewProd.Name;
                        temp.Description = NewProd.Description;
                        temp.Price = NewProd.Price;
                        temp.CategoryID = NewProd.CategoryID;
                        if(unit == "0")
                        {
                            temp.UnitWeight = NewProd.UnitWeight+"-gm";
                        }
                        else if (unit == "1")
                        {
                            temp.UnitWeight = NewProd.UnitWeight + "-kg";
                        }
                        else if (unit == "2")
                        {
                            temp.UnitWeight = NewProd.UnitWeight + "-ml";
                        }
                        else if (unit == "3")
                        {
                            temp.UnitWeight = NewProd.UnitWeight + "-L";
                        }
                        temp.Image = NewProd.Image;
                        temp.Quantity = NewProd.Quantity;
                        temp.PackgesNumber = NewProd.PackgesNumber;
                        temp.IsApproved = true;

                    }
                    else
                    {
                        temp.Name = NewProd.Name;
                        temp.Description = NewProd.Description;
                        temp.Price = NewProd.Price;
                        temp.CategoryID = NewProd.CategoryID;
                        if (unit == "0")
                        {
                            temp.UnitWeight = NewProd.UnitWeight + "-gm";
                        }
                        else if (unit == "1")
                        {
                            temp.UnitWeight = NewProd.UnitWeight + "-kg";
                        }
                        else if (unit == "2")
                        {
                            temp.UnitWeight = NewProd.UnitWeight + "-ml";
                        }
                        else if (unit == "3")
                        {
                            temp.UnitWeight = NewProd.UnitWeight + "-L";
                        }
                        temp.Quantity = NewProd.Quantity;
                        temp.PackgesNumber = NewProd.PackgesNumber;
                        temp.IsApproved = true;
                    }

                    ViewBag.cat2 = new SelectList(CategoryRepo.GetAll(), "ID", "Name");
                    ProductRepo.Add(temp);
                    TempData["alert"] = 1;
                }
            }

            catch(Exception exx)
            {
                TempData["alert"] = 5;
            }



            return Redirect("/product/Index");
        }


        [HttpGet]
        public ActionResult ProductDetails(int id)
        {
            ////////////////////////////////
            if (Session["admin"] == null)
                return Redirect("/admin/login");
            ////////////////////////////////
            ///
            ProductModel res = new ProductModel();
            string category;

            try
            {
                 res = ProductRepo.GetAll().FirstOrDefault(i => i.ID == id);
                var x = CategoryRepo.GetAll().FirstOrDefault(i => i.ID == res.CategoryID);
                category = x.Name;
                ViewBag.CategoryName = category;
            }
            catch(Exception ex)
            {
                TempData["alert"] = 5;
            }

            return View(res);
        }

        [HttpGet]
        public ActionResult Edit_Product(int id)
        {
            ////////////////////////////////
            if (Session["admin"] == null)
                return Redirect("/admin/login");
            ////////////////////////////////
            ///
            ProductModel res2 = ProductRepo.GetAll().FirstOrDefault(i => i.ID == id);
            ViewBag.cat3 = new SelectList(CategoryRepo.GetAll(), "ID", "Name");
            string[] strTemp = (res2.UnitWeight).Split('-');
            try
            {
                ViewBag.unit = strTemp[1];
                ViewBag.number = strTemp[0];
            }
            catch
            {
                return View(res2);
            }
            return View(res2);
        }


        [HttpPost]
        public ActionResult Edit_Product(ProductModel EditedProduct, HttpPostedFileBase Image2, string unit)
        {
            ////////////////////////////////
            if (Session["admin"] == null)
                return Redirect("/admin/login");
            ////////////////////////////////
            ///

            ProductModel PeforeEdited = ProductRepo.GetAll().FirstOrDefault(i => i.ID == EditedProduct.ID);
            try
            {
                    foreach (var i in ProductRepo.GetAll())                                                //check for Name unique
                    {
                        if (EditedProduct.Name == i.Name && EditedProduct.Name != PeforeEdited.Name)
                        {
                            ViewBag.existingName3 = "*This Product Is Already Existing";
                            ViewBag.cat3 = new SelectList(CategoryRepo.GetAll(), "ID", "Name");
                            return View();
                        }
                    }

                    Product res3 = new Product();

                if (!ModelState.IsValid)
                {
                    ViewBag.cat3 = new SelectList(CategoryRepo.GetAll(), "ID", "Name");
                    return View();
                }
                else
                {
                    if (Image2 != null)
                    {
                        EditedProduct.Image = new byte[Image2.ContentLength];
                        Image2.InputStream.Read(EditedProduct.Image, 0, Image2.ContentLength);

                        res3.ID = EditedProduct.ID;
                        res3.Name = EditedProduct.Name;
                        res3.CategoryID = EditedProduct.CategoryID;
                        res3.Price = EditedProduct.Price;
                        res3.Image = EditedProduct.Image;
                        if (unit == "0")
                        {

SouqElGomalAdmin/Views/product/Add_product.cshtml
@using SouqElGomalAdmin.ViewModels
@model ProductModel
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>SougEl-Gomla Admin</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sidebars/">

    <!-- CSS W3 Animation -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <!-- Bootstrap Custom styles for this template -->
    <link href="sidebars.css" rel="stylesheet">

    <style>
        #formcontainer {
            margin: 0 auto;
        }
        .field-validation-error{
            color:red;
        }
    </style>
</head>
<!------------------------------------------------------------------------------------------------->
<body style=" background-color: #DEDEDE " onload="BarFunction();" class="active">


    <!------------------------------------------------------------------------------------------------->
    <div class="row">

        <div>

            @Html.Partial("_SideBar2");
        </div>

        <div class="col-12">

            <!--add Category-->

            <div class="row">
                <!-- main -->
                <div class="col-12 col-md-10 mt-2 mb-2 border border-1 rounded" id="formcontainer" style="background-color: #FFF ">
                    <h4 class="mt-4">ADD-Product</h4>
                    <hr />

                    @using (Html.BeginForm("Add_product", "product", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {

                        @Html.LabelFor(i => i.Name);
                        @Html.TextBoxFor(i => i.Name, new { @class = "form-control" });
                        @Html.ValidationMessageFor(i => i.Name);
                        <div style="color:red;">@ViewBag.existingName2</div>

                        @Html.LabelFor(i => i.Price);
                        @Html.TextBoxFor(i => i.Price, new { @class = "form-control", type = "number", min = "0" });
                        @Html.ValidationMessageFor(i => i.Price);
                        <br />

                        @Html.Label("Category");
                        @Html.DropDownListFor(i => i.CategoryID, ViewBag.cat2 as SelectList, "--Category--", new { @class = "form-control" });
                        @Html.ValidationMessageFor(i => i.CategoryID);
                        <br />

                        @Html.LabelFor(i => i.Quantity);
                        @Html.TextBoxFor(i => i.Quantity, new { @class = "form-control", type = "number", min = "0" });
                        @Html.ValidationMessageFor(i => i.Quantity);
                        <br />


                        <div>@Html.LabelFor(i => i.UnitWeight)</div>
                        @Html.TextBoxFor(i => i.UnitWeight, new { @class = "form-control", type = "number", min = "0", style = "width:70%; float:left;" })
                        @Html.DropDownList("unit", new List<SelectListItem>{
                        new SelectListItem{Text="gm" ,Value="0" },
                        new SelectListItem{Text="kg" ,Value="1" },
                        new SelectListItem{Text="ml" ,Value="2" },
                        new SelectListItem{Text="L" ,Value="3" }
                        }, "Select Unit", new { @class = "form-control", type = "number", min = "0", style = "width:30%; float:right;" })
                        @Html.ValidationMessageFor(i => i.UnitWeight)
                        <br />
                        <br />

                        @Html.LabelFor(i => i.PackgesNumber);
                        @Html.TextBoxFor(i => i.PackgesNumber, new { @class = "form-control", type = "number", min = "0" });
                        @Html.ValidationMessageFor(i => i.PackgesNumber);
                        <br />

                        @Html.LabelFor(i => i.Description);
                        @Html.TextBoxFor(i => i.Description, new { @class = "form-control" });
                        @Html.ValidationMessageFor(i => i.Description);
                        <br />
                        <input type="file" name="Image1" accept="image/*" />
                        <br />
                        <br />

                        <input type="submit" value="Add Product" class="btn btn-primary" style="background-color:darkorange; margin:10px 0; border:1px solid darkorange" />
                    }

                </div>
            </div>

        </div>
    </div>
    <script>
        function BarFunction() {
            document.getElementById('Add_Products').setAttribute("class", "nav-link text-white active");
        }
    </script>

    <!------------------------------------------------------------------------------------------------->
    <!--Bootstrap js-->
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script>
        /* global bootstrap: false */
        (function () {
            'use strict'
            var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
            tooltipTriggerList.forEach(function (tooltipTriggerEl) {
                new bootstrap.Tooltip(tooltipTriggerEl)
            })
        })()

    </script>

    <!------------------------------------------------------------------------------------------------->

</body>
</html>

SouqElGomalAdmin/Views/product/Edit_Product.cshtml
@using SouqElGomalAdmin.ViewModels
@model ProductModel

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>SougEl-Gomla Admin</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sidebars/">

    <!-- CSS W3 Animation -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <!-- Bootstrap Custom styles for this template -->
    <link href="sidebars.css" rel="stylesheet">

    <style>
        #formcontainer {
            margin: 0 auto;
        }
        .field-validation-error {
            color: red;
        }
    </style>

</head>
<!------------------------------------------------------------------------------------------------->
<body style=" background-color: #DEDEDE " class="active">

    <div class="row">

        <div>
            @Html.Partial("_SideBar2");
        </div>

        <div class="col-12">

            <!--add Category-->

            <div class="row">
                <!-- main -->
                <div class="col-12 col-md-10 mt-2 mb-2 border border-1 rounded" id="formcontainer" style="background-color: #FFF ">
                    <h4 class="mt-4">EDIT-Product</h4>
                    <hr />

                    @using (Html.BeginForm("Edit_Product", "product", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.TextBoxFor(i => i.ID, new { @type = "hidden" });

                        @Html.LabelFor(i => i.Name);
                        @Html.TextBoxFor(i => i.Name, new { @class = "form-control", required = "required" });
                        @Html.ValidationMessageFor(i => i.Name);
                        <div style="color:red;">@ViewBag.existingName3</div>
                        <embed />

                        @Html.LabelFor(i => i.CategoryID);
                        @Html.DropDownListFor(i => i.CategoryID, ViewBag.cat3 as SelectList, "--Category--", new { @class = "form-control", required = "required" });
                        @Html.ValidationMessageFor(i => i.CategoryID);
                        <br />

                        @Html.LabelFor(i => i.Price);
                        @Html.TextBoxFor(i => i.Price, new { @class = "form-control", Type = "number", min = "0", required = "required" });
                        @Html.ValidationMessageFor(i => i.Price);
                        <br />

                        @Html.LabelFor(i => i.Quantity);
                        @Html.TextBoxFor(i => i.Quantity, new { @class = "form-control", Type = "number", min = "0", required = "required" });
                        @Html.ValidationMessageFor(i => i.Quantity);
                        <br />

                        <div>@Html.LabelFor(i => i.UnitWeight)</div>
                        @Html.TextBoxFor(i => i.UnitWeight, new { @class = "form-control", type = "number", min = "0", style = "width:70%; float:left;", value = ViewBag.number })
                        @Html.DropDownList("unit", new List<SelectListItem>{
                        new SelectListItem{Text="gm" ,Value="0" },
                        new SelectListItem{Text="kg" ,Value="1" },
                        new SelectListItem{Text="ml" ,Value="2" },
                        new SelectListItem{Text="L" ,Value="3" }
                        }, "Select Unit", new { @class = "form-control", type = "number", min = "0", style = "width:30%; float:right;", value = ViewBag.unit })
                        @Html.ValidationMessageFor(i => i.UnitWeight)
                        <br />
                        <br />

                        @Html.LabelFor(i => i.PackgesNumber);
                        @Html.TextBoxFor(i => i.PackgesNumber, new { @class = "form-control", Type = "number", min = "0", required = "required" });
                        @Html.ValidationMessageFor(i => i.PackgesNumber);
                        <br />

                        @Html.LabelFor(i => i.Description);
                        @Html.TextBoxFor(i => i.Description, new { @class = "form-control", required = "required" });
                        @Html.ValidationMessageFor(i => i.Description);
                        <br />

                        <input type="file" name="Image2" accept="image/*" />
                        <br />
                        <br />
                        <input type="submit" value="Edit Product" class="btn btn-primary" style="background-color:darkorange; margin:10px 0; border:1px solid darkorange" />
                    }

                </div>
            </div>

        </div>

    </div>
    <!------------------------------------------------------------------------------------------------->
    <!--Bootstrap js-->
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script>
            /* global bootstrap: false */
            (function () {
                'use strict'
                var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
                tooltipTriggerList.forEach(function (tooltipTriggerEl) {
                    new bootstrap.Tooltip(tooltipTriggerEl)
                })
            })()

    </script>

    <!------------------------------------------------------------------------------------------------->

</body>
</html>

SouqElGomalAdmin/Views/product/ProductDetails.cshtml
@using SouqElGomalAdmin.ViewModels
@model ProductModel

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>SougEl-Gomla Admin</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sidebars/">

    <!-- CSS W3 Animation -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <!-- Bootstrap Custom styles for this template -->
    <link href="sidebars.css" rel="stylesheet">

    <style>
        #img {
            margin: 0 auto !important;
        }

            #img > img {
                max-width: 400px;
                max-height: 400px !important;
                margin: 0 auto !important;
            }
    </style>

</head>
<body style=" background-color: #DEDEDE ">

    @if (Model.Image != null)
    {
        var base64 = Convert.ToBase64String(Model.Image);
        var imgsrc = string.Format("data:image/gif; base64,{0}", base64);

        

    <div class="card" style=" width: 50%; margin: 0 auto; margin-top: 40px;">
        <h3 style="padding:10px; margin:0auto;">Details Of Product</h3>
        <ul class="list-group list-group-flush">
            <li class="list-group-item" id="img"><img src="@imgsrc" /></li>
            <li class="list-group-item"><b>ID:</b> @Model.ID</li>
            <li class="list-group-item"><b>Name:</b> @Model.Name</li>
            <li class="list-group-item"><b>Price: </b>@Model.Price</li>
            <li class="list-group-item"><b>Quantity: </b>@Model.Quantity</li>
            <li class="list-group-item"><b>Category: </b>@ViewBag.CategoryName</li>
            <li class="list-group-item"><b>Unitweight: </b>@Model.UnitWeight</li>
            <li class="list-group-item"><b>Packges Number: </b>@Model.PackgesNumber</li>
            <li class="list-group-item"><b>Description: </b>@Model.Description</li>
        </ul>
        <a href="~/product/Index">
            <div class="card-footer btn btn-primary" style="width:100%; background-color:darkorange;">
                Back
            </div>
        </a>
    </div>
    }
    else
    {


        <div class="card" style=" width: 50%; margin: 0 auto; margin-top: 40px; margin-bottom: 40px;">
            <h3 style="padding:10px; margin:0auto;">Details Of Product</h3>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><div style="width: 400px; height: 400px; background-color: gray; margin: 0 auto;"></div></li>
                <li class="list-group-item" id="img"><img src="~/pics/NoImg.png" /></li>
                <li class="list-group-item"><b>ID:</b> @Model.ID</li>
                <li class="list-group-item"><b>Name:</b> @Model.Name</li>
                <li class="list-group-item"><b>Price: </b>@Model.Price</li>
                <li class="list-group-item"><b>Quantity: </b>@Model.Quantity</li>
                <li class="list-group-item"><b>Category: </b>@ViewBag.CategoryName</li>
                <li class="list-group-item"><b>Unitweight: </b>@Model.UnitWeight</li>
                <li class="list-group-item"><b>Packges Number: </b>@Model.PackgesNumber</li>
                <li class="list-group-item"><b>Description: </b>@Model.Description</li>
            </ul>
            <a href="~/product/Index">
                <div class="card-footer btn btn-primary" style="width: 100%; background-color: darkorange; margin-bottom: 40px;">
                    Back
                </div>
            </a>
        </div>

    }

    <!------------------------------------------------------------------------------------------------->
    <!--Bootstrap js-->
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script>
        /* global bootstrap: false */
        (function () {
            'use strict'
            var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
            tooltipTriggerList.forEach(function (tooltipTriggerEl) {
                new bootstrap.Tooltip(tooltipTriggerEl)
            })
        })()

    </script>
</body>
</html>

SouqElGomalAdmin/Views/product/Remove_product.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>SougEl-Gomla Admin</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sidebars/">

    <!-- CSS W3 Animation -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <!-- Bootstrap Custom styles for this template -->
    <link href="sidebars.css" rel="stylesheet">


</head>
<!------------------------------------------------------------------------------------------------->
<body style=" background-color: #DEDEDE ">


    <!------------------------------------------------------------------------------------------------->
    <div class="row">

        <div>
            @Html.Partial("_SideBar2");
        </div>

        <div class="col-12">
            <!--Remove Product-->
            <div class="row mt-4">
                <!-- main -->
                <div class="col-12 col-md-8 mt-2 mb-2 border border-1 rounded" id="formcontainer" style="background-color: #E2CFCF ">
                    <h4 class="mt-4">REMOVE-SUPPLIER</h4>
                    <form class="row g-3 mt-3">
                        <div class="col-md-6">
                            <label for="inputCompanyName" class="form-label">Retailer ID</label>
                            <input type="text" class="form-control" id="inputCompanyName">
                        </div>
                        <div class="col-md-6">
                            <label for="inputCompanyName" class="form-label">Confirm ID</label>
                            <input type="text" class="form-control" id="inputCompanyName">
                        </div>
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary">Remove Retailer</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>


        <!------------------------------------------------------------------------------------------------->
        <!--Bootstrap js-->
        <script src="~/Scripts/bootstrap.bundle.min.js"></script>
        <script>
            /* global bootstrap: false */
            (function () {
                'use strict'
                var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
                tooltipTriggerList.forEach(function (tooltipTriggerEl) {
                    new bootstrap.Tooltip(tooltipTriggerEl)
                })
            })()

        </script>

        <!------------------------------------------------------------------------------------------------->

</body>
</html>