SouqElGomalAdmin/Models/CategoryType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SouqElGomalAdmin.Models
{
    public class CategoryType
    {

        [Display(Name = "ID")]
        public int ID { get; set; }

        [Display(Name = "Name")]
        [Required(ErrorMessage = "*Name Required")]
        public string Name { get; set; }

        //[Display(Name = "Quantity Of Products")]
        //public int QuantityOfProducts { get; set; }

        [Display(Name = "Description ")]
        [Required(ErrorMessage = "*Description Required")]
        public string Description { get; set; }

        [Display(Name = "Image ")]
        public byte[] Image { get; set; }
    }
}

SouqElGomalAdmin/Controllers/categoriesController.cs
using SouqElGomalAdmin.Models;
using SouqElGomalAdmin.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;
using SouqElGomalAdmin.ViewModels;

namespace SouqElGomalAdmin.Controllers
{
    public class categoriesController : Controller
    {
        // GET: categories

        public ActionResult Index(int? page, string SearchBy="Name", string Search = "")
        {
            ////////////////////////////////
            if (Session["admin"] == null)
                return Redirect("/admin/login");
            ////////////////////////////////
            ///


            List<CategoryModel> res = new List<CategoryModel>() ;

            if (SearchBy == "Name")
            {
                if (Search == "")
                {
                    res = CategoryRepo.GetAll().ToList();
                }
                else
                {
                    res = CategoryRepo.GetAll().Where(i => i.Name.Contains(Search) || Search == null).ToList();
                }
            }

            //List<UserModel> res = UserRepo.GetAll();

            
            return View(res.ToPagedList(page ?? 1, 7));
        }


        [HttpGet]
        public ActionResult Add_category()
        {
            ////////////////////////////////
            if (Session["admin"] == null)
                return Redirect("/admin/login");
            ////////////////////////////////
            ///


            return View();
        }

        [HttpPost]
        public ActionResult Add_category(CategoryModel NewCategory, HttpPostedFileBase Image1)
        {
            ////////////////////////////////
            if (Session["admin"] == null)
                return Redirect("/admin/login");
            ////////////////////////////////
            ///
            try
            {
                foreach (var i in CategoryRepo.GetAll())                              //check for Name unique
                {
                    if (NewCategory.Name == i.Name)
                    {
                        ViewBag.existingName = "*This Category Is Already Existing";
                        return View();
                    }
                }

                if (!ModelState.IsValid)                                              //check for Validation
                {
                    return View();
                }

                else
                {
                    Category temp = new Category();

                    if (Image1 != null)
                    {
                        NewCategory.Image = new byte[Image1.ContentLength];
                        Image1.InputStream.Read(NewCategory.Image, 0, Image1.ContentLength);

                    
                       //temp.ID = NewCategory.ID;
                        temp.Name = NewCategory.Name;
                        temp.Description = NewCategory.Description;
                        temp.Image = NewCategory.Image;
                    }
                    else
                    {
                        //temp.ID = NewCategory.ID;
                        temp.Name = NewCategory.Name;
                        temp.Description = NewCategory.Description;
                    }

                
                    CategoryRepo.Add(temp);
                    TempData["alert"] = 3;
                }
            }
            catch(Exception es)
            {
                TempData["alert"] = 5;
                return Redirect("/categories/Index");
            }


            return Redirect("/categories/Index");
        }


        [HttpGet]
        public ActionResult CategoryDetails(int id)
        {
            ////////////////////////////////
            if (Session["admin"] == null)
                return Redirect("/admin/login");
            ////////////////////////////////
            ///


            CategoryModel res = CategoryRepo.GetAll().FirstOrDefault(i => i.ID == id);

            return View(res);
        }

        [HttpGet]
        public ActionResult Edit_category(int id)
        {
            ////////////////////////////////
            if (Session["admin"] == null)
                return Redirect("/admin/login");
            ////////////////////////////////

            CategoryModel res2 = CategoryRepo.GetAll().FirstOrDefault(i => i.ID == id);

            return View(res2);
        }


        [HttpPost]
        public ActionResult Edit_categories(CategoryModel EditedCategory, HttpPostedFileBase Image2)
        {
            ////////////////////////////////
            if (Session["admin"] == null)
                return Redirect("/admin/login");
            ////////////////////////////////
            ///
            try
            {
                if(!ModelState.IsValid)
                {
                    CategoryModel res3 = CategoryRepo.GetAll().FirstOrDefault(i => i.ID == EditedCategory.ID);

                    return View(res3);
                }
                else
                {
                    Category res3 = new Category();
                    if (Image2 != null)
                    {
                        EditedCategory.Image = new byte[Image2.ContentLength];
                        Image2.InputStream.Read(EditedCategory.Image, 0, Image2.ContentLength);


                        res3.ID = EditedCategory.ID;
                        res3.Name = EditedCategory.Name;
                        res3.Description = EditedCategory.Description;
                        res3.Image = EditedCategory.Image;
                    }
                    else
                    {
                        CategoryModel resimg = CategoryRepo.GetAll().FirstOrDefault(i => i.ID == EditedCategory.ID);

                        res3.ID = EditedCategory.ID;
                        res3.Name = EditedCategory.Name;
                        res3.Description = EditedCategory.Description;
                        res3.Image = resimg.Image;
                    }


                    CategoryRepo.Edit(res3);
                    TempData["alert"] = 4;
                }

            }
            catch(Exception er)
            {
                TempData["alert"] = 5;
                return Redirect("/categories/Index");
            }



            return Redirect("/categories/Index");
        }

        public ActionResult Delete_category(int id)
        {
            ////////////////////////////////
            if (Session["admin"] == null)
                return Redirect("/admin/login");
            ////////////////////////////////
            ///

            try
            {
                var checkQuantity = CategoryRepo.GetAll().FirstOrDefault(i => i.ID == id);


                if (checkQuantity.Products.Count() > 0)
                {
                    TempData["alert"] = 1;
                }
                if (checkQuantity.Products.Count() == 0)
                {
                    TempData["alert"] = 2;
                    CategoryRepo.Remove(id);
                }
            }
            catch(Exception ex)
            {
                TempData["alert"] = 5;
                return Redirect("/categories/Index");
            }


            return Redirect("/categories/Index");
        }
    }
}

SouqElGomalAdmin/Views/categories/Add_category.cshtml
@using SouqElGomalAdmin.ViewModels
@model CategoryModel

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>SougEl-Gomla Admin</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sidebars/">

    <!-- CSS W3 Animation -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <!-- Bootstrap Custom styles for this template -->
    <link href="sidebars.css" rel="stylesheet">

    <style>
        #formcontainer
        {
            margin: 0 auto;
        }
        .field-validation-error {
            color: red;
        }
    </style>

</head>
<!------------------------------------------------------------------------------------------------->
<body style=" background-color: #DEDEDE " onload="BarFunction();" class="active">

    <div class="row">

        <div >

            @Html.Partial("_SideBar2");
        </div>

        <div class="col-12">

            <!--add Category-->

            <div class="row">
                <!-- main -->
                <div class="col-12 col-md-10 mt-2 mb-2 border border-1 rounded" id="formcontainer" style="background-color: #fff ">
                    <h4 class="mt-4">ADD-Category</h4>
                    <hr />

                    @using (Html.BeginForm("Add_category", "categories", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {

                        @Html.LabelFor(i => i.Name);
                        @Html.TextBoxFor(i => i.Name, new { @class = "form-control" });
                        @Html.ValidationMessageFor(i => i.Name);
                        <div style="color:red;">@ViewBag.existingName</div>

                        @Html.LabelFor(i => i.Description);
                        @Html.TextBoxFor(i => i.Description, new { @class = "form-control" });
                        @Html.ValidationMessageFor(i => i.Description);
                        <br />
                        <input type="file" name="Image1" accept="image/*" />
                        <br />
                        <br />

                        <input type="submit" value="Add Category" class="btn btn-primary" style="background-color:darkorange; margin:10px 0; border:1px solid darkorange" />
                    }

                </div>
            </div>

        </div>

    </div>
    <script>
        function BarFunction() {
            document.getElementById('Add_Categories').setAttribute("class", "nav-link text-white active");
        }
    </script>
    <!------------------------------------------------------------------------------------------------->
    <!--Bootstrap js-->
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script>
        /* global bootstrap: false */
        (function () {
            'use strict'
            var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
            tooltipTriggerList.forEach(function (tooltipTriggerEl) {
                new bootstrap.Tooltip(tooltipTriggerEl)
            })
        })()

    </script>

    <!------------------------------------------------------------------------------------------------->

</body>
</html>

SouqElGomalAdmin/Views/categories/CategoryDetails.cshtml
@using SouqElGomalAdmin.ViewModels
@model CategoryModel

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>SougEl-Gomla Admin</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sidebars/">

    <!-- CSS W3 Animation -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <!-- Bootstrap Custom styles for this template -->
    <link href="sidebars.css" rel="stylesheet">

    <style>
        #img {
            margin: 0 auto !important;
        }

            #img > img {
                max-width: 400px;
                max-height: 400px !important;
                margin: 0 auto !important;
            }
    </style>

</head>
<body style=" background-color: #DEDEDE ">

    @if (Model.Image != null)
    {
        var base64 = Convert.ToBase64String(Model.Image);
        var imgsrc = string.Format("data:image/gif; base64,{0}", base64);

        

<div class="card" style=" width: 50%; margin: 0 auto; margin-top: 40px; margin-bottom: 40px;">
    <h3 style="padding:10px; margin:0auto;">Details Of Category</h3>
    <ul class="list-group list-group-flush">

        <li class="list-group-item" id="img"><img src="@imgsrc" /></li>
        <li class="list-group-item"><b>ID: </b>@Model.ID</li>
        <li class="list-group-item"><b>Name: </b>@Model.Name</li>
        <li class="list-group-item"><b>Description: </b>@Model.Description</li>
        <li class="list-group-item"><b>Quantity Of Products: </b>@Model.Products.Count()</li>
    </ul>
    <a href="~/categories/Index">
        <div class="card-footer btn btn-primary" style="width: 100%; background-color: darkorange;">
            Back
        </div>
    </a>
</div>
    }
    else
    {


        <div class="card" style=" width: 50%; margin: 0 auto; margin-top: 40px;">
            <h1>Details Of Category</h1>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><div style="width: 400px; height: 400px; background-color: gray; margin: 0 auto;"></div></li>
                <li class="list-group-item"><b>ID</b>@Model.ID</li>
                <li class="list-group-item"><b>Name</b>@Model.Name</li>
                <li class="list-group-item"><b>Description</b>@Model.Description</li>
                <li class="list-group-item"><b>Quantity Of Products</b>@Model.Products.Count()</li>
            </ul>
            <a href="~/categories/Index">
                <div class="card-footer btn btn-primary" style="width:100%; background-color:darkorange;">
                    Back
                </div>
            </a>
        </div>
    }

    <!------------------------------------------------------------------------------------------------->
    <!--Bootstrap js-->
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script>
        /* global bootstrap: false */
        (function () {
            'use strict'
            var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
            tooltipTriggerList.forEach(function (tooltipTriggerEl) {
                new bootstrap.Tooltip(tooltipTriggerEl)
            })
        })()

    </script>
</body>
</html>

SouqElGomalAdmin/Views/categories/Edit_category.cshtml
@using SouqElGomalAdmin.ViewModels
@model CategoryModel

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Sidebars · Bootstrap v5.1</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sidebars/">

    <!-- CSS W3 Animation -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <!-- Bootstrap Custom styles for this template -->
    <link href="sidebars.css" rel="stylesheet">

    <style>
        #formcontainer {
            margin: 0 auto;
        }
    </style>

</head>
<!------------------------------------------------------------------------------------------------->
<body style=" background-color: #DEDEDE ">

    <div class="row">

        <div class="col-2">
            @Html.Partial("_SideBar");
        </div>

        <div class="col-10">

            <!--add Category-->

            <div class="row">
                <!-- main -->
                <div class="col-12 col-md-10 mt-2 mb-2 border border-1 rounded" id="formcontainer" style="background-color: #FFF ">
                    <h4 class="mt-4">EDIT-Category</h4>
                    <hr />

                    @using (Html.BeginForm("Edit_categories", "categories", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.TextBoxFor(i => i.ID, new { @type = "hidden" });

                        @Html.LabelFor(i => i.Name);
                        @Html.TextBoxFor(i => i.Name, new { @class = "form-control" });
                        @Html.ValidationMessageFor(i => i.Name);

                        @Html.LabelFor(i => i.Description);
                        @Html.TextBoxFor(i => i.Description, new { @class = "form-control" });
                        @Html.ValidationMessageFor(i => i.Description);

                        <input type="file" name="Image2" />
                        <br />
                        <br />

                        <input type="submit" value="Edit Category" class="btn btn-primary" style="background-color:darkorange; margin:10px 0; border:1px solid darkorange"/>
                    }

                </div>
            </div>

        </div>

    </div>
    <!------------------------------------------------------------------------------------------------->
    <!--Bootstrap js-->
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script>
            /* global bootstrap: false */
            (function () {
                'use strict'
                var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
                tooltipTriggerList.forEach(function (tooltipTriggerEl) {
                    new bootstrap.Tooltip(tooltipTriggerEl)
                })
            })()

    </script>

    <!------------------------------------------------------------------------------------------------->

</body>
</html>

SouqElGomalAdmin/Views/categories/Index.cshtml
@using SouqElGomalAdmin.ViewModels
@using PagedList.Mvc;
@using PagedList;
@model IPagedList<CategoryModel>

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Sidebars · Bootstrap v5.1</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sidebars/">

    <!-- CSS W3 Animation -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <!-- Bootstrap Custom styles for this template -->
    <link href="sidebars.css" rel="stylesheet">

    <!--forms style-->
    <style>
        h4 {
            text-align: center;
            font-weight: bold;
        }

        .btn {
            background-color: #ed872f;
            border: #ed872f;
            color: white;
        }

            .btn:hover {
                background-color: #b54c26;
                border: #b54c26;
                color: white;
            }

            .btn.delete {
                background-color: #DC3645;
                border: #DC3645;
                color: white;
            }

                .btn.delete:hover {
                    background-color: #BC2E3C;
                    border: #BC2E3C;
                    color: white;
                }

        .container {
            background-color: #efffed;
        }

        #formcontainer,
        .card {
            background-color: #d2e7cf;
        }

        i {
            color: #ed872f;
        }

        .active {
            color: #50b141;
            text-decoration: none;
        }

            .active i {
                color: #50b141;
            }

        .nav-link {
            color: #ed872f;
        }

            .nav-link:hover {
                color: #b54c26;
            }

        * {
            font-family: Arial, Helvetica, sans-serif;
        }
        /*# sourceMappingURL=style.css.map */
    </style>

    <style>
        #formcontainer {
            margin: 0 auto;
        }


        .pagination > .active > a:not([href]):not([class]), a:not([href]):not([class]):hover {
            color: #fff;
            background-color: #f98152;
            margin: 3px;
            padding: 7px 10px;
            text-decoration: none;
        }

        .pagination > li > a {
            color: #fff;
            background-color: #fb9b50;
            margin: 3px;
            padding: 7px 10px;
            text-decoration: none;
        }
    </style>

</head>

<!------------------------------------------------------------------------------------------------->
<body style=" background-color: #DEDEDE " onload="BarFunction();">

    <!------------------------------------------------------------------------------------------------->
    <div class="row">

        <div class="col-2">
            @Html.Partial("_SideBar");
        </div>

        <div class="col-10">
            <!--Get Categories-->
            <div class="row mt-4">
                <div class="col-12 col-md-10 mt-2 mb-2 border border-1 rounded" id="formcontainer" style="background-color: #fff">
                    <h4 class="mt-4">Categories</h4>
                    <hr />

                    @using (Html.BeginForm("Index", "categories", FormMethod.Get, new { @class = "form-control" }))
                    {
                        <b>Search By: </b> @Html.RadioButton("SearchBy", "ID") <text>ID</text>
                        @Html.RadioButton("SearchBy", "Name", true) <text>Name</text> <br />
                        <span><input type="text" placeholder="Search" name="Search" class="form-control" style="width:300px; float:left;" /></span>
                        <span><input type="submit" value="Search" class="btn btn-primary" /></span>
                    }
                    <hr />
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Name</th>
                                <th scope="col">Quantity Of Products</th>
                                <th scope="col">Image</th>
                                <th scope="col">Details</th>
                                <th scope="col">Edit</th>
                                <th scope="col">Delete</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model)
                            {

                                var base64 = Convert.ToBase64String(item.Image);
                                var imgsrc = string.Format("data:image/gif; base64,{0}", base64);


                                <tr>
                                    <td>@item.ID</td>
                                    <td>@item.Name</td>
                                    <td>@item.QuantityOfProducts</td>
                                    <td>
                                        <img src="@imgsrc" style="max-width: 100px; max-height: 100px; border:solid 1px gray;" />
                                    </td>
                                    <th>@Html.ActionLink("Details", "CategoryDetails", new { id = item.ID }, new { @class = "btn btn-primary" })</th>
                                    <th>@Html.ActionLink("Edit", "Edit_category", new { id = item.ID }, new { @class = "btn btn-primary" })</th>
                                    <th>@Html.ActionLink("Delete", "Delete_category", new { id = item.ID }, new { @class = "btn btn-primary delete" })</th>

                                </tr>
                            }

                        </tbody>
                    </table>
                    <div id="Buttons">
                        @Html.PagedListPager(Model, page => Url.Action("Index", new { page })) @*Buttons of pages*@
                    </div>
                    <a href="/categories/Add_category"> <div class="btn btn-primary" style="margin:15px;"> Create Category </div> </a>
                </div>

            </div>
        </div>


    </div>
    <script>
        function BarFunction() {
            document.getElementById('Show_Categories').setAttribute("class", "nav-link text-white active");
        }
    </script>
    <!------------------------------------------------------------------------------------------------->
    <!--Bootstrap js-->
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script>
        /* global bootstrap: false */
        (function () {
            'use strict'
            var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
            tooltipTriggerList.forEach(function (tooltipTriggerEl) {
                new bootstrap.Tooltip(tooltipTriggerEl)
            })
        })()

    </script>

    <!------------------------------------------------------------------------------------------------->

</body>
</html>

SouqElGomalAdmin/Views/categories/Remove_category.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>SougEl-Gomla Admin</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sidebars/">

    <!-- CSS W3 Animation -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <!-- Bootstrap Custom styles for this template -->
    <link href="sidebars.css" rel="stylesheet">

    <style>
        #formcontainer {
            margin: 0 auto;
        }
    </style>

</head>
<!------------------------------------------------------------------------------------------------->
<body style=" background-color: #DEDEDE ">

    <div class="row">

        <div class="col-2">
            @Html.Partial("_SideBar");
        </div>

        <div class="col-10">
            <!--Remove Category-->
            <div class="row mt-4">
                <!-- main -->
                <div class="col-12 col-md-8 mt-2 mb-2 border border-1 rounded" id="formcontainer" style="background-color: #E2CFCF ">
                    <h4 class="mt-4">REMOVE-CATEGORY</h4>
                    <hr />
                    <form class="row g-3 mt-3">
                        <div class="col-md-6">
                            <label for="inputCompanyName" class="form-label">Category ID</label>
                            <input type="text" class="form-control" id="inputCompanyName">
                        </div>
                        <div class="col-md-6">
                            <label for="inputCompanyName" class="form-label">Confirm ID</label>
                            <input type="text" class="form-control" id="inputCompanyName">
                        </div>
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary">Remove Category</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

        <!------------------------------------------------------------------------------------------------->
        <!--Bootstrap js-->
        <script src="~/Scripts/bootstrap.bundle.min.js"></script>
        <script>
            /* global bootstrap: false */
            (function () {
                'use strict'
                var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
                tooltipTriggerList.forEach(function (tooltipTriggerEl) {
                    new bootstrap.Tooltip(tooltipTriggerEl)
                })
            })()

        </script>

        <!------------------------------------------------------------------------------------------------->

</body>
</html>