SouqElGomalAdmin/Models/PindingType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SouqElGomalAdmin.Models
{
    public class PindingType
    {
        [Display(Name="ID")]
        public string ID { get; set; }
        [Display(Name = "Name")]
        public string Name { get; set; }
        [Display(Name = "Address")]
        public string Address { get; set; }
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Display(Name = "User Name")]
        public string UserName { get; set; }
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
    }
}

SouqElGomalAdmin/Models/UserType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SouqElGomalAdmin.Models
{
    public class UserType
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }

        public string UserName { get; set; }

        public string PhoneNumber { get; set; }

        //[Display(Name = "Upload Image")]
        //public byte[] Image { get; set; }
        //public HttpPostedFileBase ImageFile { get; set; }
    }
}

SouqElGomalAdmin/Controllers/usersController.cs
using SouqElGomalAdmin.Repository;
using SouqElGomalAdmin.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;
using SouqElGomalAdmin.Models;
using System.IO;

namespace SouqElGomalAdmin.Controllers
{
    public class usersController : Controller
    {

        // GET: users
        public ActionResult Index(int? page, string SearchBy = "Name", string Search="")
        {
            ////////////////////////////////
            if (Session["admin"] == null)
                return Redirect("/admin/login");
            ////////////////////////////////
            ///


            List<UserModel> res = new List<UserModel>();

            if (SearchBy == "Name")
            {
                if(Search == "")
                {
                    res = UserRepo.GetAll().ToList();
                }
                else
                {
                    res = UserRepo.GetAll().Where(i => i.Name.Contains(Search) || Search == null).ToList();
                }
            }

                 
            //List<UserModel> res = UserRepo.GetAll();


            return View(res.ToPagedList(page ?? 1, 7));
        }

        public ActionResult ret(int? page)
        {
            ////////////////////////////////
            if (Session["admin"] == null)
                return Redirect("/admin/login");
            ////////////////////////////////
            ///

            //List<UserModel> res = UserRepo.GetAll().ToList();

            return View();
        }

        [HttpGet]
        public ActionResult Pinding()
        {
            ////////////////////////////////
            if (Session["admin"] == null)
                return Redirect("/admin/login");
            ////////////////////////////////
            ///

            return View();
        }

        //[HttpGet]
        //public ActionResult Add_User()
        //{
        //    return View();
        //}

        //[HttpPost]
        //public ActionResult Add_User(UserType NewUser,HttpPostedFileBase Image1)
        //{
        //    if(ModelState.IsValid)
        //    {
        //        NewUser.Image = new byte[Image1.ContentLength];
        //        Image1.InputStream.Read(NewUser.Image, 0, Image1.ContentLength);

        //        User temp = new User();

        //        temp.Id = NewUser.ID;
        //        temp.Name= NewUser.Name;
        //        temp.Email = NewUser.Email;
        //        temp.Address = NewUser.Address;
        //        temp.UserName = NewUser.UserName;
        //        temp.PhoneNumber = NewUser.PhoneNumber;
        //        temp.Image = NewUser.Image;


        //        UserRepo.Add(temp);
        //    }

        //    return Redirect("/users/Index");
        //}

        [HttpGet]
        public ActionResult UserDetails(string id)
        {
            ////////////////////////////////
            if (Session["admin"] == null)
                return Redirect("/admin/login");
            ////////////////////////////////
            ///


            UserModel res = UserRepo.GetAll().FirstOrDefault(i => i.ID == id);
            return View(res);
        }

        //[HttpGet]
        //public ActionResult Edit_User(string id)
        //{
        //    UserModel res2 = UserRepo.GetAll().FirstOrDefault(i => i.ID == id);
        //    return View(res2);
        //}


        //[HttpPost]
        //public ActionResult Edit_User(UserModel EditedUser)
        //{
        //    AspNetUser res3 = new AspNetUser();

        //    res3.Id = EditedUser.ID;
        //    res3.Name = EditedUser.Name;
        //    res3.Address= EditedUser.Address;
        //    res3.Email = EditedUser.Email;
        //    res3.UserName = EditedUser.UserName;
        //    res3.PhoneNumber = EditedUser.PhoneNumber;

        //    UserRepo.Edit(res3);

        //    return Redirect("/users/Index");
        //}

        [HttpGet]
        public ActionResult Delete_User(string id)
        {
            ////////////////////////////////
            if (Session["admin"] == null)
                return Redirect("/admin/login");
            ////////////////////////////////
            ///

            try
            {
                UserRepo.Remove(id);
            }
            catch(Exception ex)
            {
                TempData["alert"] = 1;
                return Redirect("/users/Index");
            }
            

            return Redirect("/users/Index");
        }
    }
}

SouqElGomalAdmin/Views/users/Add_User.cshtml
@using SouqElGomalAdmin.Models
@model UserType
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>SougEl-Gomla Admin</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sidebars/">

    <!-- CSS W3 Animation -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <!-- Bootstrap Custom styles for this template -->
    <link href="sidebars.css" rel="stylesheet">

    <style>
        #formcontainer {
            margin: 0 auto;
        }
    </style>

</head>
<!------------------------------------------------------------------------------------------------->
<body style=" background-color: #DEDEDE " class="active">


    <!------------------------------------------------------------------------------------------------->
    <div class="row">

        <div>
            @Html.Partial("_SideBar2");
        </div>

        <div class="col-12">

            <!--add Category-->

            <div class="row">
                <!-- main -->
                <div class="col-12 col-md-10 mt-2 mb-2 border border-1 rounded" id="formcontainer" style="background-color: #fff ">
                    <h4 class="mt-4">ADD-User</h4>
                    <hr />

                    @using (Html.BeginForm("Add_User", "users", FormMethod.Post, new { enctype="multipart/form-data"}))
                    {

                        @Html.LabelFor(i => i.Name);
                        @Html.TextBoxFor(i => i.Name, new { @class = "form-control" });
                        @Html.ValidationMessageFor(i => i.Name);

                        @Html.LabelFor(i => i.Address);
                        @Html.TextBoxFor(i => i.Address, new { @class = "form-control" });
                        @Html.ValidationMessageFor(i => i.Address);

                        @Html.LabelFor(i => i.Email);
                        @Html.TextBoxFor(i => i.Email, new { @class = "form-control" });
                        @Html.ValidationMessageFor(i => i.Email);

                        @Html.LabelFor(i => i.PhoneNumber);
                        @Html.TextBoxFor(i => i.PhoneNumber, new { @class = "form-control" });
                        @Html.ValidationMessageFor(i => i.PhoneNumber);

                        @*<input type="file" name="Image1" />*@


                        <input type="submit" value="Add User" class="btn" />
                    }

                </div>
            </div>

        </div>
    </div>

    <!------------------------------------------------------------------------------------------------->
    <!--Bootstrap js-->
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script>
        /* global bootstrap: false */
        (function () {
            'use strict'
            var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
            tooltipTriggerList.forEach(function (tooltipTriggerEl) {
                new bootstrap.Tooltip(tooltipTriggerEl)
            })
        })()

    </script>

    <!------------------------------------------------------------------------------------------------->

</body>
</html>

SouqElGomalAdmin/Views/users/Edit_User.cshtml
@using SouqElGomalAdmin.ViewModels
@model UserModel

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>SougEl-Gomla Admin</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sidebars/">

    <!-- CSS W3 Animation -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <!-- Bootstrap Custom styles for this template -->
    <link href="sidebars.css" rel="stylesheet">

    <style>
        #formcontainer {
            margin: 0 auto;
        }
    </style>

</head>
<!------------------------------------------------------------------------------------------------->
<body style=" background-color: #DEDEDE " class="active">

    <div class="row">

        <div >
            @Html.Partial("_SideBar2");
        </div>

        <div class="col-12">

            <!--add Category-->

            <div class="row">
                <!-- main -->
                <div class="col-12 col-md-10 mt-2 mb-2 border border-1 rounded" id="formcontainer" style="background-color: #FFF ">
                    <h4 class="mt-4">EDIT-User</h4>
                    <hr />

                    @using (Html.BeginForm("Edit_User", "users", "POST"))
                    {
                        <input type="hidden" value="@Model.ID" />

                        @Html.LabelFor(i => i.Name);
                        @Html.TextBoxFor(i => i.Name, new { @class = "form-control" });
                        @Html.ValidationMessageFor(i => i.Name);

                        @Html.LabelFor(i => i.Email);
                        @Html.TextBoxFor(i => i.Email, new { @class = "form-control" });
                        @Html.ValidationMessageFor(i => i.Email);

                        @Html.LabelFor(i => i.Address);
                        @Html.TextBoxFor(i => i.Address, new { @class = "form-control" });
                        @Html.ValidationMessageFor(i => i.Address);

                        @Html.LabelFor(i => i.UserName);
                        @Html.TextBoxFor(i => i.UserName, new { @class = "form-control" });
                        @Html.ValidationMessageFor(i => i.UserName);

                        @Html.LabelFor(i => i.PhoneNumber);
                        @Html.TextBoxFor(i => i.PhoneNumber, new { @class = "form-control" });
                        @Html.ValidationMessageFor(i => i.PhoneNumber);


                        <input type="submit" value="Edit User" class="btn btn-primary" />
                    }

                </div>
            </div>

        </div>

    </div>
    <!------------------------------------------------------------------------------------------------->
    <!--Bootstrap js-->
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script>
            /* global bootstrap: false */
            (function () {
                'use strict'
                var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
                tooltipTriggerList.forEach(function (tooltipTriggerEl) {
                    new bootstrap.Tooltip(tooltipTriggerEl)
                })
            })()

    </script>

    <!------------------------------------------------------------------------------------------------->

</body>
</html>

SouqElGomalAdmin/Views/users/Index.cshtml
@using SouqElGomalAdmin.ViewModels
@using PagedList.Mvc;
@using PagedList;
@model IPagedList<UserModel>

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>SougEl-Gomla Admin</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sidebars/">

    <!-- CSS W3 Animation -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <!-- Bootstrap Custom styles for this template -->
    <link href="sidebars.css" rel="stylesheet">


    <!--forms style-->
    <style>
        h4 {
            text-align: center;
            font-weight: bold;
        }

        .btn {
            background-color: #ed872f;
            border: #ed872f;
            color: white;
        }

            .btn:hover {
                background-color: #b54c26;
                border: #b54c26;
                color: white;
            }

            .btn.delete {
                background-color: #DC3645;
                border: #DC3645;
                color: white;
            }

         .btn.delete:hover {
            background-color: #BC2E3C;
            border: #BC2E3C;
            color: white;
         }

        .container {
            background-color: #efffed;
        }

        #formcontainer,
        .card {
            background-color: #d2e7cf;
        }

        i {
            color: #ed872f;
        }

        .active {
            color: #50b141;
            text-decoration: none;
        }

            .active i {
                color: #50b141;
            }

        .nav-link {
            color: #ed872f;
        }

            .nav-link:hover {
                color: #b54c26;
            }

        * {
            font-family: Arial, Helvetica, sans-serif;
        }
        /*# sourceMappingURL=style.css.map */
    </style>

    <style>
        #formcontainer {
            margin: 0 auto;
        }


        .pagination > .active > a:not([href]):not([class]), a:not([href]):not([class]):hover {
            color: #fff;
            background-color: #f98152;
            margin: 3px;
            padding: 7px 10px;
            text-decoration: none;
        }

        .pagination > li > a {
            color: #fff;
            background-color: #fb9b50;
            margin: 3px;
            padding: 7px 10px;
            text-decoration: none;
        }
        .displayNone {
            display: none;
        }



    </style>
</head>
<!------------------------------------------------------------------------------------------------->
<body style=" background-color: #DEDEDE " onload="BarFunction();" class="active">
    <div class="row">

        <div class="col-0">
            @Html.Partial("_SideBar2");

        </div>

        <div class="col-12">

            <!--Get Users-->
            <div class="row">
                <div class="col-12 col-md-10 mt-2 mb-2 border border-1 rounded" id="formcontainer" style="background-color: #fff">
                    <h4 class="mt-4">Users</h4>


                    <hr />


                    @if ((TempData["alert"]) == null)
                    {

                    }
                    else
                    {
                        if (((int)TempData["alert"]) == 1)
                        {
                            <div class="alert alert-danger" role="alert">
                                Can't Remove This User'
                            </div>
                        }
                    }
                        @using (Html.BeginForm("Index", "users", FormMethod.Get, new { @class = "form-control" }))
                        {
                            <span><input type="text" placeholder="Search By Name" name="Search" class="form-control" style="width:300px; float:left;" /></span>
                            <span><input type="submit" value="Search" class="btn btn-primary" /></span>
                        }
                        <hr />

                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Details</th>
                                    <th class="displayNone">Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var i in Model)
                                {
                                    if (i.Image != null)
                                    {
                                        var base64 = Convert.ToBase64String(i.Image);
                                        var imgsrc = string.Format("data:image/gif; base64,{0}", base64);


                                        <tr>
                                            <td>@i.ID</td>
                                            <td>@i.Name</td>
                                            <th>@Html.ActionLink("Details", "UserDetails", new { id = i.ID }, new { @class = "btn btn-primary" })</th>
                                            <th class="displayNone">@Html.ActionLink("Delete", "Delete_User", new { id = i.ID }, new { @class = "btn btn-primary  delete" })</th>

                                        </tr>
                                    }

                                    else
                                    {
                                        <tr>
                                            <td>@i.ID</td>
                                            <td>@i.Name</td>
                                            <th>@Html.ActionLink("Details", "UserDetails", new { id = i.ID }, new { @class = "btn btn-primary" })</th>
                                            <th class="displayNone">@Html.ActionLink("Delete", "Delete_User", new { id = i.ID }, new { @class = "btn btn-primary  delete" })</th>

                                        </tr>
                                    }
                                }

                            </tbody>
                        </table>
                        <div id="Buttons">
                            @Html.PagedListPager(Model, page => Url.Action("Index", new { page })) @*Buttons of pages*@
                        </div>
                    </div>
            </div>
            
        </div>
    </div>
    <script>
        function BarFunction() {
            document.getElementById('Show_Users').setAttribute("class", "nav-link text-white active");
        }
    </script>

    <!------------------------------------------------------------------------------------------------->
    <!--Bootstrap js-->
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script>
        /* global bootstrap: false */
        (function () {
            'use strict'
            var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
            tooltipTriggerList.forEach(function (tooltipTriggerEl) {
                new bootstrap.Tooltip(tooltipTriggerEl)
            })
        })()

    </script>


    <!------------------------------------------------------------------------------------------------->
</body>
</html>

SouqElGomalAdmin/Views/users/Pinding.cshtml
@using SouqElGomalAdmin.Models
@model UserType


<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>SougEl-Gomla Admin</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sidebars/">

    <!-- CSS W3 Animation -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <!-- Bootstrap Custom styles for this template -->
    <link href="sidebars.css" rel="stylesheet">


    <!--forms style-->
    <style>
        h4 {
            text-align: center;
            font-weight: bold;
        }

        .btn {
            background-color: #ed872f;
            border-radius: 3rem;
            font-size: 1rem;
            width: 150px;
            height: 48px;
            color: white;
        }

            .btn:hover {
                background-color: #b54c26;
            }

        .container {
            background-color: #efffed;
        }

        #formcontainer,
        .card {
            background-color: #d2e7cf;
        }

        i {
            color: #ed872f;
        }

        .active {
            color: #50b141;
            text-decoration: none;
        }

            .active i {
                color: #50b141;
            }

        .nav-link {
            color: #ed872f;
        }

            .nav-link:hover {
                color: #b54c26;
            }

        * {
            font-family: Arial, Helvetica, sans-serif;
        }
        /*# sourceMappingURL=style.css.map */
    </style>

</head>
<!------------------------------------------------------------------------------------------------->
<body style=" background-color: #f7f7f7 ">

    <div class="row">

        <div class="col-2">
            @Html.Partial("_SideBar");
        </div>

        <div class="col-10">

            <!--add suplier-->

            @using (Html.BeginForm("Add_User", "users", "POST"))
            {
                @Html.LabelFor(i => i.ID);
                @Html.TextBoxFor(i => i.ID, new { @class = "form-control" });
                @Html.ValidationMessageFor(i => i.ID);

                @Html.LabelFor(i => i.Name);
                @Html.TextBoxFor(i => i.Name, new { @class = "form-control" });
                @Html.ValidationMessageFor(i => i.Name);

                @Html.LabelFor(i => i.Email);
                @Html.TextBoxFor(i => i.Email, new { @class = "form-control" });
                @Html.ValidationMessageFor(i => i.Name);

                @Html.LabelFor(i => i.Address);
                @Html.TextBoxFor(i => i.Address, new { @class = "form-control" });
                @Html.ValidationMessageFor(i => i.Name);

                @Html.LabelFor(i => i.UserName);
                @Html.TextBoxFor(i => i.UserName, new { @class = "form-control" });
                @Html.ValidationMessageFor(i => i.Name);

                @Html.LabelFor(i => i.PhoneNumber);
                @Html.TextBoxFor(i => i.PhoneNumber, new { @class = "form-control" });
                @Html.ValidationMessageFor(i => i.Name);


                <input type="submit" value="Add User" class="btn" />
            }

        </div>
    </div>



        <!------------------------------------------------------------------------------------------------->
        <!--Bootstrap js-->
        <script src="~/Scripts/bootstrap.bundle.min.js"></script>
        <script>
            /* global bootstrap: false */
            (function () {
                'use strict'
                var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
                tooltipTriggerList.forEach(function (tooltipTriggerEl) {
                    new bootstrap.Tooltip(tooltipTriggerEl)
                })
            })()

        </script>


        <!------------------------------------------------------------------------------------------------->
</body>
</html>

SouqElGomalAdmin/Views/users/Remove_User.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>SougEl-Gomla Admin</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sidebars/">

    <!-- CSS W3 Animation -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <!-- Bootstrap Custom styles for this template -->
    <link href="sidebars.css" rel="stylesheet">


    <!--forms style-->
    <style>
        h4 {
            text-align: center;
            font-weight: bold;
        }

        .btn {
            background-color: #ed872f;
            border-radius: 3rem;
            font-size: 1rem;
            width: 150px;
            height: 48px;
            color: white;
        }

            .btn:hover {
                background-color: #b54c26;
            }

        .container {
            background-color: #efffed;
        }

        #formcontainer,
        .card {
            background-color: #d2e7cf;
        }

        i {
            color: #ed872f;
        }

        .active {
            color: #50b141;
            text-decoration: none;
        }

            .active i {
                color: #50b141;
            }

        .nav-link {
            color: #ed872f;
        }

            .nav-link:hover {
                color: #b54c26;
            }

        * {
            font-family: Arial, Helvetica, sans-serif;
        }
        /*# sourceMappingURL=style.css.map */
    </style>

</head>
<!------------------------------------------------------------------------------------------------->
<body style=" background-color: #DEDEDE ">

    <div class="row">

        <div class="col-2">
            @Html.Partial("_SideBar");
        </div>

        <div class="col-10">

            <div class="row mt-4">
                <!-- main -->
                <div class="col-12 col-md-8 mt-2 mb-2 border border-1 rounded" id="formcontainer" style="background-color: #E2CFCF ">
                    <h4 class="mt-4">REMOVE-RETAILER</h4>
                    <form class="row g-3 mt-3">
                        <div class="col-md-6">
                            <label for="inputCompanyName" class="form-label">Retailer ID</label>
                            <input type="text" class="form-control" id="inputCompanyName">
                        </div>
                        <div class="col-md-6">
                            <label for="inputCompanyName" class="form-label">Confirm ID</label>
                            <input type="text" class="form-control" id="inputCompanyName">
                        </div>
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary">Remove Retailer</button>
                        </div>
                    </form>
                </div>
            </div>

            <!--Remove Suplier-->
            <div class="row mt-4">
                <!-- main -->
                <div class="col-12 col-md-8 mt-2 mb-2 border border-1 rounded" id="formcontainer" style="background-color: #E2CFCF ">
                    <h4 class="mt-4">REMOVE-SUPPLIER</h4>
                    <form class="row g-3 mt-3">
                        <div class="col-md-6">
                            <label for="inputCompanyName" class="form-label">Suplier ID</label>
                            <input type="text" class="form-control" id="inputCompanyName">
                        </div>
                        <div class="col-md-6">
                            <label for="inputCompanyName" class="form-label">Confirm ID</label>
                            <input type="text" class="form-control" id="inputCompanyName">
                        </div>
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary">Remove supplier</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>


        <!------------------------------------------------------------------------------------------------->
        <!--Bootstrap js-->
        <script src="~/Scripts/bootstrap.bundle.min.js"></script>
        <script>
            /* global bootstrap: false */
            (function () {
                'use strict'
                var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
                tooltipTriggerList.forEach(function (tooltipTriggerEl) {
                    new bootstrap.Tooltip(tooltipTriggerEl)
                })
            })()

        </script>


        <!------------------------------------------------------------------------------------------------->
</body>
</html>

SouqElGomalAdmin/Views/users/ret.cshtml
@using SouqElGomalAdmin.ViewModels
@using PagedList.Mvc;
@using PagedList;
@model IPagedList<UserModel>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SougEl-Gomla Admin</title>
</head>
<body>
    <table class="table">
        <thead>
            <tr>
                <th>
                    name
                </th>
                <th>
                    img
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var i in Model)
            {
                var base64 = Convert.ToBase64String(i.Image);
                var imgsrc = string.Format("data:image/gif; base64,{0}", base64);



                <tr>
                    <td>
                        @i.Name;
                    </td>
                    <td>
                        <img src="@imgsrc" style="max-width: 100px; max-height: 100px;" />
                    </td>
                </tr>
            }

        </tbody>
        <div id="Buttons">
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page })) @*Buttons of pages*@
        </div>
    </table>
</body>
</html>